# theme.py

'''
Core module for managing application aesthetics. This class handles 
loading, parsing, and applying color palettes from JSON files or 
predefined internal defaults using PySide6's QPalette system.
'''

# Accessing standard library for handling structured JSON theme files
import json

# Accessing standard library for filesystem navigation and path validation
import os

# UI components for building dialogs and invoking the system file explorer
from PySide6.QtWidgets import QDialog, QFileDialog # type: ignore

# Classes for programmatic color manipulation and UI palette management
from PySide6.QtGui import QPalette, QColor # type: ignore

# Core Qt constants for alignment and common global settings
from PySide6.QtCore import Qt # type: ignore


'''
Integration of local modules for logging diagnostics and 
loading UI layouts generated by Qt Designer.
'''

# Base class providing logging functionality for error and info tracking
from libs.Logging.logging import Logging

# Pre-compiled Python class representing the Theme Dialog interface
from libs.QtGuiFiles.PyFiles.ThemeDialog import Ui_ThemeDialog


# Theme class responsible for the visual style and dynamic skinning of the app
class Theme(Logging):

    # Initializes the theme manager and discovers available theme resources
    def __init__(self) -> None:
        '''
        Initializes parents and prepares the environment for theme selection.
        Sets up default internal palettes and the themes directory path.
        '''

        # Invoke the constructor of the Logging parent class
        super().__init__()

        # Map string identifiers to anonymous functions that generate specific palettes
        self.defaultThemes = {
            "Dark": lambda: self.loadPalette("Dark"),
            "Light": lambda: self.loadPalette("Light")
        }

        # Define the relative filesystem path where JSON theme files are located
        self.themeDir = "resources/Themes"


        # Assign the method reference for theme discovery to an instance variable
        self.themes = self._getThemes

        # Execute the discovery method to populate theme data immediately
        self.themes()


    '''
    Internal helper methods for UI interaction and filesystem scanning.
    '''

    # Triggers a system file dialog to let the user pick a theme file manually
    def _browseThemes(self) -> None:

        # Launch an Open File dialog restricted to Python and JSON files
        filename, _ = QFileDialog.getOpenFileName(
            self,
            # Window title for the file picker
            "Choose file",
            # Starting path (defaults to the application root)
            "",  
            # File type filter for the dialog
            "Python files (*.py);;"
        )

        # Populate the input field in the UI with the chosen file path
        self.ui.addLineEdit.setText(filename)


    # Scans the themes directory and compiles a list of available JSON theme files
    def _getThemes(self) -> list:

        # Create a local list to hold the discovered filenames
        themes = []

        # Iterate over every entry found in the defined theme directory
        for theme in os.listdir(self.themeDir):

            # Filter out directories to ensure we only process files
            if not os.path.isdir(f"{self.themeDir}/{theme}"):

                # Identify valid theme files by their .json extension
                if theme.endswith(".json"):

                    # Add the verified filename string to our collection
                    themes.append(str(theme))

        # Return the finalized list of theme filenames to the caller
        return themes


    # Validates and prepares a new theme for integration based on a file path
    def _addTheme(self, path) -> None:

        # Set the feedback label color to red to indicate potential errors
        self.ui.statusLabel.setStyleSheet("color: #ff0000")

        # Verify that the user actually provided a string in the input field
        if not path:

            # Update the status label to notify the user of the missing input
            self.ui.statusLabel.setText("Enter path!")

            # Abort the addition process
            return

        # Use the OS module to check if the provided path exists on the disk
        if not os.path.exists(path):

            # Notify the user that the specified file cannot be found
            self.ui.statusLabel.setText("Path does not exists!")

            # Abort the addition process
            return 

        # Finalize the operation by closing the active theme dialog
        self.close()


    '''
    External interface methods for managing and applying application styles.
    '''

    # Constructs and displays the modal dialog for theme management
    def getTheme(self) -> None:
        '''
        Sets up the theme dialog window, links signals to slots, 
        and executes the modal interface.
        '''

        # Create the top-level dialog container
        themeDialog = QDialog()

        # Instantiate the auto-generated UI class for this dialog
        themeDialogUi = Ui_ThemeDialog()

        # Build the visual components onto the dialog instance
        themeDialogUi.setupUi(themeDialog)


        '''
        Configuring window metadata and geometry constraints.
        '''

        # Define the text that appears in the dialog's title bar
        themeDialog.setWindowTitle("Add theme")

        # Restrict the window from being smaller than its content requires
        themeDialog.setMinimumSize(themeDialog.sizeHint())

        # Resize the dialog to its optimal initial dimensions
        themeDialog.resize(themeDialog.sizeHint())


        '''
        Binding UI events to specific logic handlers.
        '''

        # Connect the browse button click to the file explorer logic
        themeDialogUi.browseButton.clicked.connect(self._browseThemes)

        # Connect the add button to the validation logic using the input's text
        themeDialogUi.addButton.clicked.connect(lambda: self._addTheme(themeDialogUi.addLineEdit.text()))

        # Start the dialog's event loop and block until it is closed
        themeDialog.exec()


    # Transforms a JSON structure into a functional Qt color palette
    def parsePalette(self, palette):

        # Guard clause to ensure the file exists and has a JSON extension
        if not os.path.exists(f"{self.theme_dir}/{palette}") or not palette.endswith(".json"):

            # Log a critical error message via the Logging parent class
            self.printe(msg=f"Wrong palette {palette}", exception=None, function=self.parseJSONPalette.__name__)

            # Exit the method with a failure status
            return False
        
        # Open the filesystem resource in read-only mode
        with open(f"{self.theme_dir}/{palette}", "r") as theme:

            # Convert the raw JSON text into a Python dictionary
            data = json.load(theme)
            
        # Initialize a fresh QPalette instance to be populated
        palette = QPalette()


        # Safe block to catch missing keys in the JSON theme definition
        try:

            # Mapping text and label colors from the dictionary to the palette
            palette.setColor(QPalette.WindowText, data["QPalette.WindowText"])

            # Map the standard foreground color for text widgets
            palette.setColor(QPalette.Text, data["QPalette.Text"])

            # Map the color for text displayed on buttons
            palette.setColor(QPalette.ButtonText, data["QPalette.ButtonText"])

            # Map the color for highly contrasting or highlighted text
            palette.setColor(QPalette.BrightText, data["QPalette.BrightText"])

            # Map the color for non-interactive hint text in inputs
            palette.setColor(QPalette.PlaceholderText, data["QPalette.PlaceholderText"])


            # Mapping background and surface colors
            palette.setColor(QPalette.Window, data["QPalette.Window"])

            # Map the primary background for data entry fields
            palette.setColor(QPalette.Base, data["QPalette.Base"])

            # Map the secondary background for alternating row colors
            palette.setColor(QPalette.AlternateBase, data["QPalette.AlternateBase"])

            # Map the main background color for button elements
            palette.setColor(QPalette.Button, data["QPalette.Button"])

            # Map the background of hovering help tooltips
            palette.setColor(QPalette.ToolTipBase, data["QPalette.ToolTipBase"])

            # Map the text color inside help tooltips
            palette.setColor(QPalette.ToolTipText, data["QPalette.ToolTipText"])


            # Mapping decorative 3D effects and shadowing
            palette.setColor(QPalette.Shadow, data["QPalette.Shadow"])

            # Map the lightest color for 3D highlights
            palette.setColor(QPalette.Light, data["QPalette.Light"])

            # Map the mid-light shading level
            palette.setColor(QPalette.Midlight, data["QPalette.Midlight"])

            # Map the neutral middle shading level
            palette.setColor(QPalette.Mid, data["QPalette.Mid"])

            # Map the darkest shading level for deep shadows
            palette.setColor(QPalette.Dark, data["QPalette.Dark"])


            # Mapping interaction and link colors
            palette.setColor(QPalette.Highlight, data["QPalette.Highlight"])

            # Map the color of text inside selected areas
            palette.setColor(QPalette.HighlightedText, data["QPalette.HighlightedText"])

            # Map the default color for interactive hyperlinks
            palette.setColor(QPalette.Link, data["QPalette.Link"])

            # Map the color for links that have been visited
            palette.setColor(QPalette.LinkVisited, data["QPalette.LinkVisited"])


            # Mapping specific colors for inactive/disabled UI states
            palette.setColor(QPalette.Disabled, QPalette.WindowText, data["Disabled.WindowText"])

            # Map disabled general text
            palette.setColor(QPalette.Disabled, QPalette.Text, data["Disabled.Text"])

            # Map disabled button text
            palette.setColor(QPalette.Disabled, QPalette.ButtonText, data["Disabled.ButtonText"])

            # Map disabled field background
            palette.setColor(QPalette.Disabled, QPalette.Base, data["Disabled.Base"])


            # Successfully return the fully configured QPalette object
            return palette

        # Exception handler for malformed JSON theme files
        except KeyError as e:

            # Log the specific missing attribute that caused the failure
            self.printe(msg=f"Error while loading palette {palette}", exception=e, function=self.parseJSONPalette.__name__)

            # Return failure status to prevent application styling errors
            return False


    # Generates a standard hardcoded Dark or Light palette
    def loadPalette(self, palette):

        # Configuration for the high-contrast Dark theme
        if palette == "Dark":

            # Create a new palette instance for dark mode
            dark_palette = QPalette()


            # Set the primary dark gray for main window surfaces
            background_color = QColor(45, 45, 45)

            # Set a slightly darker shade for contrast in lists
            alternate_background = QColor(35, 35, 35)

            # Set a soft white for primary reading text
            text_color = QColor(225, 225, 225)

            # Set a mid-gray for inactive interface elements
            disabled_color = QColor(127, 127, 127)

            # Set a vibrant blue for focus indicators and selections
            highlight_color = QColor(42, 130, 218) 


            # Apply color constants to the dark palette roles
            dark_palette.setColor(QPalette.Window, background_color)

            # Assign text color
            dark_palette.setColor(QPalette.WindowText, text_color)

            # Assign input field background
            dark_palette.setColor(QPalette.Base, QColor(25, 25, 25))

            # Assign secondary list background
            dark_palette.setColor(QPalette.AlternateBase, alternate_background)

            # Define tooltip surface color
            dark_palette.setColor(QPalette.ToolTipBase, Qt.white)

            # Define tooltip text color
            dark_palette.setColor(QPalette.ToolTipText, Qt.white)

            # Define general foreground text
            dark_palette.setColor(QPalette.Text, text_color)

            # Define button surface color
            dark_palette.setColor(QPalette.Button, background_color)

            # Define button label color
            dark_palette.setColor(QPalette.ButtonText, text_color)

            # Define critical error text color
            dark_palette.setColor(QPalette.BrightText, Qt.red)

            # Define hyperlink color
            dark_palette.setColor(QPalette.Link, highlight_color)

            # Define selection background
            dark_palette.setColor(QPalette.Highlight, highlight_color)

            # Define selection text color for optimal contrast
            dark_palette.setColor(QPalette.HighlightedText, Qt.black)


            # Define visual rules for disabled widgets in dark mode
            dark_palette.setColor(QPalette.Disabled, QPalette.WindowText, disabled_color)

            # Assign disabled text foreground
            dark_palette.setColor(QPalette.Disabled, QPalette.Text, disabled_color)

            # Assign disabled button labels
            dark_palette.setColor(QPalette.Disabled, QPalette.ButtonText, disabled_color)

            # Assign disabled input background
            dark_palette.setColor(QPalette.Disabled, QPalette.Base, background_color)


            # Return the fully defined dark mode palette
            return dark_palette

        # Configuration for the standard Light theme
        elif palette == "Light":

            # Create a new palette instance for light mode
            light_palette = QPalette()


            # Set the light gray standard background
            background_color = QColor(240, 240, 240)

            # Set a slightly darker gray for visual separation in UI
            alternate_background = QColor(225, 225, 225)

            # Set pure white for input areas
            base_color = QColor(255, 255, 255)

            # Set solid black for primary text
            text_color = QColor(0, 0, 0)

            # Set a soft gray for disabled text
            disabled_color = QColor(160, 160, 160)

            # Set the classic Windows blue for highlights
            highlight_color = QColor(0, 120, 215) 


            # Apply color constants to the light palette roles
            light_palette.setColor(QPalette.Window, background_color)

            # Assign main text color
            light_palette.setColor(QPalette.WindowText, text_color)

            # Assign white background for input fields
            light_palette.setColor(QPalette.Base, base_color)

            # Assign alternate background color
            light_palette.setColor(QPalette.AlternateBase, alternate_background)

            # Define tooltip appearance
            light_palette.setColor(QPalette.ToolTipBase, Qt.white)

            # Define tooltip text appearance
            light_palette.setColor(QPalette.ToolTipText, text_color)

            # Define general text color
            light_palette.setColor(QPalette.Text, text_color)

            # Define button color
            light_palette.setColor(QPalette.Button, background_color)

            # Define text on buttons
            light_palette.setColor(QPalette.ButtonText, text_color)

            # Define attention text color
            light_palette.setColor(QPalette.BrightText, Qt.red)

            # Define link appearance
            light_palette.setColor(QPalette.Link, highlight_color)

            # Define selection appearance
            light_palette.setColor(QPalette.Highlight, highlight_color)

            # Define selected text color
            light_palette.setColor(QPalette.HighlightedText, Qt.white)


            # Define visual rules for disabled widgets in light mode
            light_palette.setColor(QPalette.Disabled, QPalette.WindowText, disabled_color)

            # Set disabled foreground text
            light_palette.setColor(QPalette.Disabled, QPalette.Text, disabled_color)

            # Set disabled button text
            light_palette.setColor(QPalette.Disabled, QPalette.ButtonText, disabled_color)

            # Set disabled base background
            light_palette.setColor(QPalette.Disabled, QPalette.Base, background_color)


            # Return the complete light mode palette
            return light_palette

        # Return nothing if an unknown palette name is passed
        else: None